# ⚗️ Cathedral of Circuits - Coolify Configuration
# Magnum Opus Version 1.0
# Author: Rebecca Respawn
# React + Vite + Turbo Monorepo

version: "3.8"

services:
  cathedral-web:
    build:
      context: .
      dockerfile: Dockerfile.coolify
      args:
        - NODE_VERSION=20
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./apps/web/dist:/app/dist:ro
      - ./apps/web/public:/app/public:ro
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - cathedral-network

networks:
  cathedral-network:
    driver: bridge

