packages:
  # Local packages in this workspace only
  - 'packages/*'
  - 'apps/*'
  
  # Note: Other workspaces are integrated via workspace integrator, not pnpm workspace
  # to avoid duplicate package conflicts
